### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by V-Dewan** [mwilko/OOP1MWILKO#2]
- Code is properly commented on and allows me to understand the logic used in the program.
- Errors are handled perfectly. After inputting test values such as letters, symbols and numbers such as '-999', it provides the user with an error message and allows the user to input another value until it is acceptable.

![Screenshot 2023-03-05 at 09 36 42](https://user-images.githubusercontent.com/126815273/222953107-4885349b-6358-4c1d-9b28-0eadc95a186e.png)

- You have not shown the suit of the cards, e.g., the cards dealt are outputted as such: '4-4', '11-1' '5-2'. If the user asks to be dealt only one card and gets the result '4-4', they will be confused as to which number is the number/suit of the card. 

![Screenshot 2023-03-05 at 09 44 58](https://user-images.githubusercontent.com/126815273/222953423-7aae601c-592d-4d5c-bef4-91327f20a1b6.png)

- Therefore, you could output a message that tells the user that the number on the right is the suit of the card and show what the number represents, e.g., the number '4' being Spades. Or, if possible, you could implement a feature to output it as such: '4-Spades'.

VIbin Dewan
26506937

**Comment by mwilko** [comment]
Thanks for the review Vibin, 

Due to the criteria listing the Suits and Values as integer data types i couldn't alter change the Suit to a string such as "Hearts", although, to solve this issue i have altered the output function to take the integer value. With this value i set a string variable to a certain suit and then added it to the outputted message. As shown below: 

<img width="598" alt="Screenshot 2023-03-05 at 21 44 20" src="https://user-images.githubusercontent.com/123997833/222987803-6e9d4b6d-b151-47ca-8e78-636ee228b872.png">

<img width="288" alt="Screenshot 2023-03-05 at 21 45 14" src="https://user-images.githubusercontent.com/123997833/222987813-b7126491-e455-4658-9b59-0e4aebe903de.png">
